### ISSUE TITLE
Type of load in ACMeasurement

### ISSUE THREAD

**Issue by danielvillalbamota** [smart-data-models/harmonization#3]
This issue is a question about the incubated data model [ACMeasurement](https://github.com/smart-data-models/harmonization/tree/master/ACMeasurement)

In buildings it is common to distribute the electric measurements between the different type of load (bulbs, fans/ACC, plugs). Is there any attribute to describe this property? In case there isn't, would it be interesting to include it.

A kind of property "typeOfLoad" with a list of elements: lighting, air conditioning, plugs?

**Comment by albertoabellagarcia** [comment]
it's interesting the idea. But what it is the difference from the array of relationships in "refDevice" which are pointing to the elements related to the AC Measurement?

**Comment by danielvillalbamota** [comment]
I see the "typeOfLoad" property as part of ACMeasurement because the relationship with the "Device" (meter) could change or even not been available. I understand ACMeasurement attached to the electric line but the Device (meter) could change, I'll explain it:
- If we use the IoT Agent to transport the data from the Device (meter) to the ACMeasurement entity we could not been instantiated the Device in the Context Broker, so it would be interesting to have the "typeOfLoad" property attached to the ACMeasurement.
- Similar to the first point but if we do have the Device instantiated in the CB and the relationship ACMeasurement-refDevice, the Device could be changed for some reason but the ACMeasurement entity would remain the same (attached to line).

Does it make sense?

**Comment by albertoabellagarcia** [comment]
yes it make sense, then make a PR with this.
